### ISSUE TITLE
Add Color setting in Settings

### ISSUE THREAD

**Issue by NeoJoris** [notspiff/screensaver.matrixtrails#22]
Please add acolor setting, 

I know the green is special from the matrix trilogy, but it doesn't fit with other surrounding elements in the living room. 

label:enhancement

**Comment by AlwinEsch** [comment]
I look to bring it in.

**Comment by AlwinEsch** [comment]
Have added here https://github.com/xbmc/screensaver.matrixtrails/pull/21 and on another for Leia something to select color.

**Comment by AlwinEsch** [comment]
Changes are in, thanks for the request, make sense to have.
